// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoVPyrStoFbT9KDajY0ePMo4-O8j9WC9I',
    appId: '1:750102676526:web:7e8343a70c8b7787314bbf',
    messagingSenderId: '750102676526',
    projectId: 'inventory-app-aryan-sahu',
    authDomain: 'inventory-app-aryan-sahu.firebaseapp.com',
    storageBucket: 'inventory-app-aryan-sahu.firebasestorage.app',
    measurementId: 'G-JSCY0L6HGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jvm_WQz2yOf-b59RDoyAbnVwpaer88k',
    appId: '1:750102676526:android:db748641c82a89eb314bbf',
    messagingSenderId: '750102676526',
    projectId: 'inventory-app-aryan-sahu',
    storageBucket: 'inventory-app-aryan-sahu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzD-Txv094chlf0JqSi8NWFKvXgKRfhcg',
    appId: '1:750102676526:ios:9dd754f37ad157dc314bbf',
    messagingSenderId: '750102676526',
    projectId: 'inventory-app-aryan-sahu',
    storageBucket: 'inventory-app-aryan-sahu.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzD-Txv094chlf0JqSi8NWFKvXgKRfhcg',
    appId: '1:750102676526:ios:9dd754f37ad157dc314bbf',
    messagingSenderId: '750102676526',
    projectId: 'inventory-app-aryan-sahu',
    storageBucket: 'inventory-app-aryan-sahu.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoVPyrStoFbT9KDajY0ePMo4-O8j9WC9I',
    appId: '1:750102676526:web:9f5f91a2378c287f314bbf',
    messagingSenderId: '750102676526',
    projectId: 'inventory-app-aryan-sahu',
    authDomain: 'inventory-app-aryan-sahu.firebaseapp.com',
    storageBucket: 'inventory-app-aryan-sahu.firebasestorage.app',
    measurementId: 'G-N0ZC1H1B7D',
  );
}
